# Rayhan Mahmud 

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,34,1]],np.int64)

In [3]:
myarr[0,1]

np.int64(6)

In [4]:
print(myarr)

[[ 3  6 34  1]]


In [5]:
myarr.shape

(1, 4)

In [6]:
 myarr.dtype

dtype('int64')

In [7]:
myarr[0,2] = 45

In [8]:
myarr

array([[ 3,  6, 45,  1]])

In [9]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
zeros = np.zeros((3,5))

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
lspace = np.linspace(1,10,3)

In [16]:
lspace

array([ 1. ,  5.5, 10. ])

In [17]:
arr = np.arange(100).reshape(10,10)

In [18]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
arr.reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
zeros = np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
zeros.shape

(2, 5)

In [23]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,100,5)

In [26]:
lspace

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [27]:
ide = np.identity(5)

In [28]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
arr = np.arange(56)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [31]:
arr = arr.reshape(7,8)

In [32]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55])

In [34]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [35]:
arr = np.array(x)

In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.sum(axis=0)

array([12, 15, 18])

In [38]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [39]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [40]:
arr.flat

In [41]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [42]:
arr.ndim

2

In [43]:
arr.size

9

In [44]:
arr.nbytes

72

In [45]:
one = np.array([5, 17, 3, 17, 8, 20, 11, 12, 11, 11, 14, 6, 7, 5, 16, 15, 17, 13, 13, 17])

In [46]:
one.argmax()

np.int64(5)

In [47]:
one.argmin()

np.int64(2)

In [48]:
 one.argsort()

array([ 2,  0, 13, 11, 12,  4,  8,  6,  9,  7, 18, 17, 10, 15, 14,  1, 16,
        3, 19,  5])

In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.argmin()

np.int64(0)

In [51]:
arr.argmax()

np.int64(8)

In [52]:
arr.argmax(axis=1)

array([2, 2, 2])

In [53]:
arr.argmax(axis=0)

array([2, 2, 2])

In [54]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
arr.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr2 = np.array([[4,5,6],[1,2,3],[7,8,9]])

In [58]:
arr2

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [59]:
arr + arr2

array([[ 5,  7,  9],
       [ 5,  7,  9],
       [14, 16, 18]])

In [60]:
arr * arr2

array([[ 4, 10, 18],
       [ 4, 10, 18],
       [49, 64, 81]])

In [61]:
np.sqrt(arr2)

array([[2.        , 2.23606798, 2.44948974],
       [1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.82842712, 3.        ]])

In [62]:
np.nonzero(arr2)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [63]:
np.count_nonzero(arr2)

9